kube-prometheus-stack:
  grafana:
    enabled: true
    adminPassword: admin123
    nodeSelector:
      type: dependent_services
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://observability-loki:3100
        access: proxy
    service:
      type: NodePort
      nodePort: 32000
  prometheus:
    prometheusSpec:
      nodeSelector:
        type: dependent_services
      additionalScrapeConfigs:
        - job_name: blackbox-argocd
          metrics_path: /probe
          params:
            module: [http_2xx]
          static_configs:
            - targets:
                - http://argocd-server.argocd.svc.cluster.local:80
                - http://vault.vault.svc.cluster.local:8200
                - http://student-api-service.student-api.svc.cluster.local:5000/api/v1/students
          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: observability-prometheus-blackbox-exporter:9115
        - job_name: postgres-exporter
          static_configs:
            - targets:
                - observability-prometheus-postgres-exporter:9187
  alertmanager:
    enabled: false
  nodeExporter:
    enabled: true
    tolerations:
      - operator: Exists
  kubeStateMetrics:
    enabled: true
    nodeSelector:
      type: dependent_services
  prometheusOperator:
    nodeSelector:
      type: dependent_services

loki:
  deploymentMode: SingleBinary
  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    storage:
      type: filesystem
    schemaConfig:
      configs:
        - from: "2024-01-01"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    ruler:
      enable_api: false
      storage:
        type: local
        local:
          directory: /var/loki/rules
  singleBinary:
    replicas: 1
    nodeSelector:
      type: dependent_services
    podSecurityContext:
      fsGroup: 10001
      runAsGroup: 10001
      runAsNonRoot: true
      runAsUser: 10001
  persistence:
    enabled: true
    size: 1Gi
    storageClass: standard
  chunksCache:
    enabled: false
  resultsCache:
    enabled: false
  backend:
    replicas: 0
  read:
    replicas: 0
  write:
    replicas: 0

promtail:
  defaultVolumes:
    - name: run
      hostPath:
        path: /run/promtail
    - name: containers
      hostPath:
        path: /var/lib/docker/containers
    - name: pods
      hostPath:
        path: /var/log/pods
  defaultVolumeMounts:
    - name: run
      mountPath: /run/promtail
    - name: containers
      mountPath: /var/lib/docker/containers
      readOnly: true
    - name: pods
      mountPath: /var/log/pods
      readOnly: true
  readinessProbe:
    failureThreshold: 100
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 30
    periodSeconds: 10
  config:
    clients:
      - url: http://observability-loki:3100/loki/api/v1/push
    snippets:
      scrapeConfigs: |
        - job_name: kubernetes-pods
          kubernetes_sd_configs:
            - role: pod
          pipeline_stages:
            - docker: {}
            - match:
                selector: '{app!="student-api"}'
                action: drop
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_node_name]
              target_label: __host__
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - source_labels: [__meta_kubernetes_namespace]
              target_label: namespace
            - source_labels: [__meta_kubernetes_pod_name]
              target_label: pod
            - source_labels: [__meta_kubernetes_pod_container_name]
              target_label: container
            - replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
                - __meta_kubernetes_pod_uid
                - __meta_kubernetes_pod_container_name
              target_label: __path__

prometheus-blackbox-exporter:
  nodeSelector:
    type: dependent_services
  config:
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          valid_status_codes: []
          method: GET

prometheus-postgres-exporter:
  nodeSelector:
    type: dependent_services
  config:
    datasource:
      host: postgres-service.student-api.svc.cluster.local
      user: postgres
      password: postgres
      database: student_db
      sslmode: disable
