apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
    spec:
      nodeSelector:
        type: application
      containers:
      - name: api
        image: student-api:1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: database_url
        - name: FLASK_APP
          value: "app"
        - name: FLASK_ENV
          value: "development"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: secret_key
