name: CI Pipeline

on:
  push:
    paths:
      - 'milestone-1-student-api/**'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Python
        run: python --version

      - name: Install dependencies
        run: |
          cd milestone-1-student-api
          make install

      - name: Run tests
        run: |
          cd milestone-1-student-api
          make test

      - name: Run linting
        run: |
          cd milestone-1-student-api
          make lint

      - name: Docker login
        run: |
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Docker build and push
        run: |
          cd milestone-1-student-api
          docker build -t ${{ secrets.DOCKER_USERNAME }}/student-api:1.0.0 .
          docker push ${{ secrets.DOCKER_USERNAME }}/student-api:1.0.0