apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
    spec:
      nodeSelector:
        type: {{ .Values.nodeSelector.type }}
      containers:
      - name: api
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.externalSecret.targetName }}
              key: secret_key
