apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-external-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: {{ .Values.externalSecret.secretStoreKind }}
  target:
    name: {{ .Values.externalSecret.targetName }}
    creationPolicy: Owner
  data:
  - secretKey: db_password
    remoteRef:
      key: secret/student-api
      property: db_password
  - secretKey: secret_key
    remoteRef:
      key: secret/student-api
      property: secret_key
  - secretKey: db_url
    remoteRef:
      key: secret/student-api
      property: db_url
